version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.11
    steps:
      - checkout
      - run:
          name: gradlew 권한 부여
          command: chmod +x ./gradlew
      - run:
          name: gradle 빌드
          command: ./gradlew build
      - persist_to_workspace:
          root: .
          paths:
            - .

  docker-build-deploy:
    docker:
      - image: cimg/base:current
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: default
      - run:
          name: Docker Login
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build --file docker/Dockerfile --tag $DOCKERHUB_USERNAME/$DOCKER_IMAGE_TAG_NAME:latest .
      - run:
          name: Push Docker image
          command: |
            docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE_TAG_NAME:latest

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh ubuntu@$SSH_HOST "docker/deploy.sh"

workflows:
  build_and_push:
    jobs:
      - build
      - docker-build-deploy:
          requires:
            - build
      - deploy:
          requires:
            - docker-build-deploy
