# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config

# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.11
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: gradlew 권한 부여
          command: chmod +x ./gradlew
      - run:
          name: gradle 빌드
          command: ./gradlew build
  docker-build-deploy:
    docker:
      - image: cimg/base:current
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: Docker Login
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - run:
          name: Build Docker image
          command: |
            docker build . --file docker/Dockerfile --tag $DOCKERHUB_USERNAME/filter-pattern2:latest
      - run:
          name: Push Docker image
          command: |
            docker push $DOCKERHUB_USERNAME/filter-pattern2:latest

## Orchestrate jobs using workflows
## See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build_and_push:
    jobs:
      - build
      - docker-build-deploy:
          requires:
            - build