version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.11
    steps:
      - checkout
      - run:
          name: gradlew 권한 부여
          command: chmod +x ./gradlew
      - run:
          name: gradle 빌드
          command: ./gradlew build
      - persist_to_workspace:
          root: .
          paths:
            - .

  docker-build-deploy:
    docker:
      - image: cimg/base:current
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: default
      - run:
          name: Docker Login
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build --file /docker/Dockerfile --tag $DOCKERHUB_USERNAME/$DOCKER_IMAGE_TAG_NAME:latest .
      - run:
          name: Push Docker image
          command: |
            docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE_TAG_NAME:latest

  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "SHA256:G0hvj9P5Usfd8d8b/fnQX/082Ztd7ROIycKPv71NC6U"
      - run:
          name: Deploy Over SSH
          command: ssh -o StrictHostKeyChecking=no ubuntu@$SSH_HOST "bash /docker/deploy.sh"

workflows:
  build_and_push:
    jobs:
      - build
      - docker-build-deploy:
          requires:
            - build
      - deploy:
          requires:
            - docker-build-deploy
