on:
  push:
    branches: [ gitaction2 ]

env:
  DOCKER_IMAGE_TAG_NAME: filter-pattern

jobs:
  build-and-docker-push:
    runs-on: ubuntu-20.04 # 실행환경

    # 실행 스텝 지정
    steps:
      - uses: actions/checkout@v3

      # java version 지정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build
      - name: Build with Gradle
        run: ./gradlew clean build

      - name: copy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./build/libs/*.jar"
          target: "~"

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Checking for running Java processes..."
            PID=$(pgrep -f 'java -jar')
            if [ -n "$PID" ]; then
              echo "Killing existing Java process with PID $PID"
              kill -9 $PID
            else
              echo "No running Java process found"
            fi
            echo "Starting new Java process"
            nohup java -jar *.jar > ~/java_app.log 2>&1 &
            echo "Java process started"